esphome:
  name: crayon

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret crayon_api_key

ota:
  - platform: esphome
    password: !secret crayon_ota_password

wifi:
  ssid: !secret crayon_wifi_ssid
  password: !secret crayon_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Crayon Fallback Hotspot"
    password: "password"

captive_portal:

# Button input on GPIO3
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    on_press:
      then:
        - if:
            condition:
              light.is_on: rgb_light
            then:
              - light.turn_off:
                  id: rgb_light
                  transition_length: 2s
            else:
              - light.turn_on:
                  id: rgb_light
                  transition_length: 2s
                  color_brightness: 80%
              - delay: 2s
              - light.turn_on:
                  id: rgb_light
                  effect: "Rainbow"

# RGB LED on GPIO0, 1, 2
output:
  - platform: ledc
    pin: GPIO0
    id: output_green
  - platform: ledc
    pin: GPIO1
    id: output_blue
  - platform: ledc
    pin: GPIO3
    id: output_red

light:
  - platform: rgb
    name: "RGB Light"
    id: rgb_light
    red: output_red
    green: output_green
    blue: output_blue
    
    effects:
      - random:
          name: "Random Color"
          transition_length: 5s
          update_interval: 7s
      - flicker:
      - lambda:
          name: "Rainbow"
          update_interval: 6.0s
          # {"c":"#bd5bff","n":8,"tr":5500,"up":6000,"name":"Rainbow","id":"rgb_light"}
          lambda: |-
            static int state = 0;
            auto call = id(rgb_light).turn_on();
            call.set_transition_length(5500);
            switch (state) {
              case 0:
                call.set_rgb(0.7, 0.4, 1.0);
                break;
              case 1:
                call.set_rgb(1.0, 0.4, 0.8);
                break;
              case 2:
                call.set_rgb(1.0, 0.4, 0.4);
                break;
              case 3:
                call.set_rgb(1.0, 0.9, 0.4);
                break;
              case 4:
                call.set_rgb(0.6, 1.0, 0.4);
                break;
              case 5:
                call.set_rgb(0.4, 1.0, 0.6);
                break;
              case 6:
                call.set_rgb(0.4, 0.9, 1.0);
                break;
              case 7:
              default:
                call.set_rgb(0.4, 0.5, 1.0);
                break;
            }
            call.set_publish(true);
            call.set_save(false);
            call.perform();
            state += 1;
            if (state >= 8)
              state = 0;
      - strobe:
          name: "Nodus"
          colors:
            - brightness: 100%
              red: 100%
              green: 86%
              blue: 0%
              duration: 4s
            - brightness: 0%
              red: 0%
              green: 0%
              blue: 0%
              duration: 4s
            - brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              duration: 4s
